import type { TweakConfig } from "@/shared/types";

export const DEFAULTS: TweakConfig = {
  showChat: true,
  showLowerThird: true,
  showTopBar: true,
  showCornerLogo: true,
  showTicker: true,
  showLiveBadge: true,
  showHeartParticles: true,
  scene: "two-cams",
  startingVariant: "v1",
  quoteVariant: "editorial",
  quoteText:
    "A melhor tecnologia é aquela que some — você só percebe que ela existe quando para de funcionar.",
  quoteAuthor: "Marina Costa",
  quoteAuthorRole: "Senior Frontend Engineer",
  quoteContext: "Sobre design de APIs",
  questionAuthor: "jpcoder",
  questionAuthorBadge: "SUB",
  questionText:
    "Vale a pena começar com Rust em 2026 mesmo sem experiência com sistemas de baixo nível?",
  questionFrom: "twitch.tv/he4rttalks",
  questionQueue: 12,
  pollQuestion: "O que você usaria pra começar um projeto novo em 2026?",
  pollTotalVotes: 1847,
  pollTimeLeft: "01:24",
  brbDuration: 120,
  brbTrack: "lo-fi beats to debug to · vol. 4",
  screenContent: "code",
  screenTitle: "live-coding · refactor da API de auth",
  startCountdown: 180,
  endMessage: "Valeu por hoje, galera!",
  startingTitle: "A LIVE COMEÇA EM",
  startingSubtitle: "Senta que o papo vai longe ☕",
  startingCountdownSeconds: 300,
  endingTitle: "ESSA COMUNIDADE É TUDO.",
  endingSubtitle:
    "Algumas das mensagens que vocês mandaram durante a live de hoje. Cada palavra foi lida — obrigado por bancar o projeto.",
  nextEpisodeNumber: "EP. 043",
  nextEpisodeTitle: "Open Source paga as contas?",
  nextEpisodeGuest: "com Gabi Santos · Maintainer Bun.js",
  nextEpisodeDate: "QUI · 19 DEZ · 20H",
  endStatViewers: 2847,
  endStatMessages: 1284,
  endStatSubs: 142,
  endStatQuestions: 38,
  primary: "#7C3AED",
  primaryDeep: "#5B21B6",
  accent: "#A855F7",
  bgDeep: "#0B0418",
  bgPanel: "#160A2A",
  panelOpacity: 0.78,
  guest1Name: "Marina Costa",
  guest1Role: "Senior Frontend Engineer",
  guest1Handle: "@marinacosta.dev",
  guest2Name: "Lucas Pereira",
  guest2Role: "Host · Heart Talks",
  guest2Handle: "@lucas.he4rt",
  episodeTitle: "Cervejinha e bate papo",
  episodeNumber: "EP. 042",
  topic: "Carreira, comunidade e o futuro do dev BR",
  date: "12 DE DEZEMBRO",
  time: "20H",
  tickerText:
    "PRÓXIMO BLOCO · pergunte ao vivo em discord.app/he4rt   ●   Use #he4rttalks no X   ●   Inscreva-se no canal pra não perder",
  chatTitle: "CHAT AO VIVO",
};
